DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS artist;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL
);

CREATE TABLE artist (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id INTEGER NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  name TEXT NOT NULL,
  rating REAL,
  FOREIGN KEY (user_id) REFERENCES user (id),
  UNIQUE(user_id, name)
);
