DROP TABLE IF EXISTS hearrd_user CASCADE;
DROP TABLE IF EXISTS rating;

CREATE TABLE hearrd_user (
  id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  username TEXT UNIQUE NOT NULL
);

CREATE TABLE rating (
  id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  user_id INTEGER NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  type TEXT NOT NULL,
  name TEXT NOT NULL,
  value REAL,
  FOREIGN KEY (user_id) REFERENCES hearrd_user (id),
  UNIQUE(user_id, type, name)
);
